### ISSUE TITLE
python_code 디렉터리에 경북일보 지진관련 기사 크롤링 파일 업로드

### ISSUE THREAD

**Issue by kimsunu** [public-big-data-internship-project/Analysis-of-Seismic-Hazard#6]
경북일보 지진관련 기사 크롤링 코드작성

**Comment by MHhw** [comment]
제목수정
python_code 디렉터리에 광주 광역시 건축 데이터 전처리 파일 업로드 ->python_code 디렉터리에 경북일보 지진관련 기사 크롤링 코드 업로드

**Comment by kimsunu** [comment]
경북일보 크롤링 코드 재작성
search 키워드 ="지진피해"
