### ISSUE TITLE
python_code 디렉터리에 중앙일보 지진 관련 기사 크롤링 코드 업로드

### ISSUE THREAD

**Issue by eeminkkk** [public-big-data-internship-project/Analysis-of-Seismic-Hazard#7]
중앙일보 지진 관련 기사 크롤링 코드 작성
"한반도 지진 피해"

**Comment by MHhw** [comment]
제목수정
python_code 디렉터리에 광주 광역시 건축 데이터 전처리 파일 업로드 ->python_code 디렉터리에 중앙일보 지진 관련 기사 크롤링 코드 업로드
